baseUrl: /
languageCode: en-us
theme: terminal
paginate: 5
DefaultContentLanguage: en

params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: posts
  # ["orange", "blue", "red", "green", "pink"]
  themeColor: green
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 3
  # show selector to switch language
  showLanguageSelector: true
  # set theme to full screen width
  fullWidthTheme: false
  # center theme with default width
  centerTheme: false
  favicon: /favicon.ico

languages:
  en:
    languageName: english
    title: thecodecousins
    subtitle: Anything that's software
    tagline: A software blog that runs in the true spirit of open-source
    keywords: 'blog, software, software-engineering, technology, code'
    menuMore: show more
    readMore: read more
    readOtherPosts: read other posts

    params:
      logo:
        logoText: thecodecousins
        logoHomeLink: /

    menu:
      main:
        - identifier: about
          name: about
          url: /about
        - identifier: contribute
          name: contribute
          url: /contribute
  vi:
    languageName: viet
    title: thecodecousins
    subtitle: Miễn là phần mềm
    keywords: ''
    menuMore: xem thêm
    readMore: đọc thêm
    readOtherPosts: đọc bài khác

    params:
      logo:
        logoText: thecodecousins
        logoHomeLink: /vi

    menu:
      main:
        - identifier: about
          name: giới thiệu
          url: /vi/about
        - identifier: contribute
          name: đóng góp
          url: /vi/contribute
